version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "uv run python manage.py migrate &&
             uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DOCKER_ENV=1

volumes:
  sqlite_data:
