# Generated by Django 5.2.4 on 2025-07-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunityInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ko", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("vision_ko", models.TextField()),
                ("vision_en", models.TextField()),
                ("mission_ko", models.TextField()),
                ("mission_en", models.TextField()),
                ("discord_invite_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Community Information",
                "verbose_name_plural": "Community Information",
            },
        ),
        migrations.CreateModel(
            name="ContributionOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("organizer", "Organizer"),
                            ("speaker", "Speaker"),
                            ("study_leader", "Study Leader"),
                            ("sponsor", "Sponsor"),
                            ("volunteer", "Volunteer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title_ko", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ko", models.TextField()),
                ("description_en", models.TextField()),
                ("requirements_ko", models.TextField(blank=True)),
                ("requirements_en", models.TextField(blank=True)),
                ("contact_method_ko", models.TextField()),
                ("contact_method_en", models.TextField()),
                ("is_open", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["type", "title_ko"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ko", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ko", models.TextField()),
                ("description_en", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("seminar", "Seminar"),
                            ("workshop", "Workshop"),
                            ("meetup", "Meetup"),
                            ("networking", "Networking"),
                        ],
                        default="seminar",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location_ko", models.CharField(blank=True, max_length=200)),
                ("location_en", models.CharField(blank=True, max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("joining", "Joining"),
                            ("participation", "Participation"),
                            ("technical", "Technical"),
                            ("contact", "Contact"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("question_ko", models.CharField(max_length=200)),
                ("question_en", models.CharField(max_length=200)),
                ("answer_ko", models.TextField()),
                ("answer_en", models.TextField()),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=100)),
                ("name_en", models.CharField(max_length=100)),
                ("role_ko", models.CharField(max_length=100)),
                ("role_en", models.CharField(max_length=100)),
                ("bio_ko", models.TextField(blank=True)),
                ("bio_en", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="organizers/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name_ko"],
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ko", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("description_ko", models.TextField()),
                ("description_en", models.TextField()),
                (
                    "meeting_schedule_ko",
                    models.CharField(help_text="e.g., Every Tuesday 7PM", max_length=200),
                ),
                (
                    "meeting_schedule_en",
                    models.CharField(help_text="e.g., Every Tuesday 7PM", max_length=200),
                ),
                ("is_recruiting", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
