# Generated by Django 5.2.4 on 2025-07-08 13:06

import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0002_activity_socialmediaplatform_delete_communityinfo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediaplatform",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("main_channel", "메인 채널"),
                    ("publication_platform", "발행 플랫폼"),
                ],
                db_comment="Type of the link (main channel or publication platform)",
                default="main_channel",
                max_length=20,
                verbose_name="링크 유형",
            ),
        ),
        migrations.CreateModel(
            name="ActivityPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "publication_url",
                    models.URLField(
                        db_comment="URL of the specific publication post",
                        verbose_name="게시물 URL",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Date and time when the activity was published",
                        null=True,
                        verbose_name="게시 일시",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        db_comment="Reference to the activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="main.activity",
                        verbose_name="활동",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        db_comment="Reference to the social media platform",
                        limit_choices_to={"link_type": "publication_platform"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.socialmediaplatform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "활동 게시물",
                "verbose_name_plural": "활동 게시물",
                "db_table_comment": "Links activities to their social media publications",
                "ordering": ["-published_at", "platform__order"],
                "unique_together": {("activity", "platform")},
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="published_on",
            field=models.ManyToManyField(
                related_name="published_activities",
                through="main.ActivityPublication",
                to="main.socialmediaplatform",
                verbose_name="발행된 플랫폼",
            ),
        ),
    ]
